__init__.py
from flask import Flask

# Se crea una instancia de la aplicación Flask
application = Flask(__name__, template_folder='templates', static_url_path="/static")

# Se importan los módulos de la aplicación
from controllers import mod

# Se registran los módulos de la aplicación en la instancia de la aplicación Flask
application.register_blueprint(mod)

if __name__ == '__main__':
    # Se inicia el servidor web de Flask
    application.run()

app.py
from flask import Flask, redirect, render_template
from data import delete_all_documents, analyze_average_popularity_per_album, Mongo_Song_Data
from spotify import app_Authorization, user_Authorization, Profile_Data, Playlist_Data, Song_Data

app = Flask(__name__, static_url_path='/static', template_folder='static/assets')

@app.route("/")
def index():
    # Authorization
    return render_template("index.html")

@app.route("/login")
def login():
    # Authorization
    auth_url = app_Authorization()
    return redirect(auth_url)

@app.route("/callback")
def callback():
    authorization_header = user_Authorization()

    #Gathering of profile data
    profile_data = Profile_Data(authorization_header)
    user_id = profile_data["id"]
    Name = profile_data["display_name"]
    external_urls = profile_data["external_urls"]
    uri = profile_data["uri"]
    href = profile_data["href"]
    followers = profile_data["followers"]["total"]
    images = profile_data["images"]

    #Gathering of playlist data
    playlist_data = Playlist_Data(authorization_header,profile_data)
    
    x = 0
    playlist_url = []
    playlist_titles = []
    playlist_track_count = []
    playlist_track_url = []
    songs = []
    while x < len(playlist_data["items"]):
        playlist_track_count.insert(len(playlist_track_count),playlist_data["items"][x]["tracks"]['total'])
        playlist_url.insert(len(playlist_url),playlist_data["items"][x]["tracks"]['href'])
        playlist_titles.insert(len(playlist_titles),playlist_data["items"][x]["name"])
        playlist_track_url.insert(len(playlist_track_url),playlist_data["items"][x]["tracks"]['href'])
        x = x + 1
    for items in playlist_data["items"]:
        playlist_name = items["name"]
        url = items["tracks"]["href"]
        song_data = Song_Data(authorization_header,url)
        for song in song_data["items"]:
            songs.insert(
                len(songs),
                {
                    "id":song["track"]["id"],
                    "name":song["track"]["name"],
                    "artist":song["track"]["artists"][0]["name"],
                    "playlist_name":playlist_name,
                    "added_at":song["added_at"],
                    "user_id":user_id,
                    "duration_ms":song["track"]["duration_ms"],
                    "popularity":song["track"]["popularity"],
                    "explicit":song["track"]["explicit"],
                    "amount_available_markets":len(song["track"]["available_markets"]),
                }
            )

    delete_all_documents({'info.user_id': user_id})
    Mongo_Song_Data(songs)
    avg_per_playlist = analyze_average_popularity_per_album(user_id)
    return render_template("playlist.html", avg_per_playlist=avg_per_playlist)

if __name__ == "__main__":
    app.run(debug = True, port=4000, host="localhost")

app/app.py
from flask import Flask, redirect, render_template
from data import delete_all_documents, analyze_average_popularity_per_album, Mongo_Song_Data
from spotify import app_Authorization, user_Authorization, Profile_Data, Playlist_Data, Song_Data

app = Flask(__name__, template_folder='templates', static_url_path="/static")

@app.route("/")
def index():
    # Authorization
    return render_template("index.html")

@app.route("/login")
def login():
    # Authorization
    auth_url = app_Authorization()
    return redirect(auth_url)

@app.route("/callback")
def callback():
    authorization_header = user_Authorization()

    #Gathering of profile data
    profile_data = Profile_Data(authorization_header)
    user_id = profile_data["id"]
    Name = profile_data["display_name"]
    external_urls = profile_data["external_urls"]
    uri = profile_data["uri"]
    href = profile_data["href"]
    followers = profile_data["followers"]["total"]
    images = profile_data["images"]

    #Gathering of playlist data
    playlist_data = Playlist_Data(authorization_header,profile_data)
    
    x = 0
    playlist_url = []
    playlist_titles = []
    playlist_track_count = []
    playlist_track_url = []
    songs = []
    while x < len(playlist_data["items"]):
        playlist_track_count.insert(len(playlist_track_count),playlist_data["items"][x]["tracks"]['total'])
        playlist_url.insert(len(playlist_url),playlist_data["items"][x]["tracks"]['href'])
        playlist_titles.insert(len(playlist_titles),playlist_data["items"][x]["name"])
        playlist_track_url.insert(len(playlist_track_url),playlist_data["items"][x]["tracks"]['href'])
        x = x + 1
    for items in playlist_data["items"]:
        playlist_name = items["name"]
        url = items["tracks"]["href"]
        song_data = Song_Data(authorization_header,url)
        for song in song_data["items"]:
            songs.insert(
                len(songs),
                {
                    "id":song["track"]["id"],
                    "name":song["track"]["name"],
                    "artist":song["track"]["artists"][0]["name"],
                    "playlist_name":playlist_name,
                    "added_at":song["added_at"],
                    "user_id":user_id,
                    "duration_ms":song["track"]["duration_ms"],
                    "popularity":song["track"]["popularity"],
                    "explicit":song["track"]["explicit"],
                    "amount_available_markets":len(song["track"]["available_markets"]),
                }
            )

    delete_all_documents({'info.user_id': user_id})
    Mongo_Song_Data(songs)
    avg_per_playlist = analyze_average_popularity_per_album(user_id)
    return render_template("playlist.html", avg_per_playlist=avg_per_playlist)

if __name__ == "__main__":
    app.run(debug = True, port=4000, host="localhost")

controllers.py
from flask import Blueprint, render_template, redirect, session
from spotify import app_Authorization, user_Authorization, Profile_Data, Playlist_Data, Song_Data, logout
import pandas as pd

# Se crea un objeto Blueprint para definir las rutas asociadas a este módulo.
mod = Blueprint('controllers', __name__, url_prefix='')

# Se define una ruta para la página de inicio de la aplicación.
@mod.route("/")
def index():
    return render_template("index.html")

@mod.route("/login")
def login():
    # Authorization
    auth_url = app_Authorization()
    session["auth_url"] = auth_url

    return redirect(auth_url)

@mod.route("/callback")
def callback():
    authorization_header = user_Authorization()
    session["authorization_header"] = authorization_header

    #Gathering of profile data
    profile_data = Profile_Data(authorization_header)
    user_id = profile_data["id"]
    user_name = profile_data["display_name"]

    playlist_data = Playlist_Data(authorization_header,profile_data)
    avg_dicts = []
    final_result = []
    for items in playlist_data["items"]:
        playlist_name = items["name"]
        playlist_url = items["external_urls"]["spotify"]
        url = items["tracks"]["href"]
        song_data = Song_Data(authorization_header,url)
        for song in song_data["items"]:

            avg_dicts.append({
                    "id":song["track"]["id"],
                    "name":song["track"]["name"],
                    "artist":song["track"]["artists"][0]["name"],
                    "playlist_name":playlist_name,
                    "playlist_url":playlist_url,
                    "added_at":song["added_at"],
                    "user_id":user_id,
                    "user_name":user_name,
                    "duration_ms":song["track"]["duration_ms"],
                    "popularity":song["track"]["popularity"],
                    "explicit":song["track"]["explicit"],
                    "amount_available_markets":len(song["track"]["available_markets"]),
                })
        
        df = pd.DataFrame(avg_dicts)
        avg_per_playlist = df.groupby(["playlist_name", "playlist_url"]).mean()["popularity"]

    for row in avg_per_playlist.iteritems():
        final_result.append({"playlist_name":row[0][0], "playlist_url":row[0][1], "avg_popularity":"{:.2f}".format(row[1])})
    # return str(final_result)
    return render_template("playlist.html", avg_per_playlist=final_result)

@mod.route("/logout")
def logout():
    session.pop("access_token", None)
    session.clear()
    return redirect("/")

templates/index.html
<!doctype html>
<html>
  <head>
    <title>Playlists average</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css')}}">
  </head>

  <body>
    <div class="container">
      <h1>
        ¡Tu música es única y especial!
      </h1>
      <p>
        Descubre qué tan popular es tu playlist con nuestro promedio de popularidad. ¡Inicia sesión en Spotify ahora!
      </p>
      <a href="/login">
        <button>
          Ingresa con Spotify
        </button>
      </a>
      </div>

    <script id="user-profile-template" type="text/x-handlebars-template"></script>
    <script id="oauth-template" type="text/x-handlebars-template"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0-alpha.1/handlebars.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script>
      (function() {

        /**
         * Obtains parameters from the hash of the URL
         * @return Object
         */
        function getHashParams() {
          var hashParams = {};
          var e, r = /([^&;=]+)=?([^&;]*)/g,
              q = window.location.hash.substring(1);
          while ( e = r.exec(q)) {
             hashParams[e[1]] = decodeURIComponent(e[2]);
          }
          return hashParams;
        }

        var userProfileSource = document.getElementById('user-profile-template').innerHTML,
            userProfileTemplate = Handlebars.compile(userProfileSource),
            userProfilePlaceholder = document.getElementById('user-profile');

        var oauthSource = document.getElementById('oauth-template').innerHTML,
            oauthTemplate = Handlebars.compile(oauthSource),
            oauthPlaceholder = document.getElementById('oauth');

        var params = getHashParams();

        var access_token = params.access_token,
            refresh_token = params.refresh_token,
            error = params.error;

        if (error) {
          alert('There was an error during the authentication');
        } else {
          if (access_token) {
            // render oauth info
            oauthPlaceholder.innerHTML = oauthTemplate({
              access_token: access_token,
              refresh_token: refresh_token
            });

            $.ajax({
                url: 'https://api.spotify.com/v1/me',
                headers: {
                  'Authorization': 'Bearer ' + access_token
                },
                success: function(response) {
                  userProfilePlaceholder.innerHTML = userProfileTemplate(response);

                  $('#login').hide();
                  $('#loggedin').show();
                }
            });
          } else {
              // render initial screen
              $('#login').show();
              $('#loggedin').hide();
          }

          document.getElementById('obtain-new-token').addEventListener('click', function() {
            $.ajax({
              url: '/refresh_token',
              data: {
                'refresh_token': refresh_token
              }
            }).done(function(data) {
              access_token = data.access_token;
              oauthPlaceholder.innerHTML = oauthTemplate({
                access_token: access_token,
                refresh_token: refresh_token
              });
            });
          }, false);
        }
      })();
    </script>
  </body>
</html>

templates/playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css')}}">
  <link rel="stylesheet" href="../static/css/app.css">
  <title>Document</title>
</head>
<body>
  <div id="header">
    <h1>Spotify Playlist Analyzer</h1>
    <a href="{{ url_for('controllers.logout') }}" id="cerrar-sesion">Cerrar sesión</a>
  </div>
  
  <div id="playlist">
  <!-- <script src="../static/js/index.js"></script> -->
  <script>
    var json_str = '{{ avg_per_playlist | tojson }}';
    var data = JSON.parse(json_str);
    var recetlyPllayed = document.getElementById("playlist");
    var list = document.createElement("ul");

    for (var i = 0; i < data.length; i++) {
      var playlist_name = data[i].playlist_name;
      var playlist_url = data[i].playlist_url;
      var average_popularity = data[i].avg_popularity;

      if (average_popularity > 70){
        var Comentario = document.createTextNode('Esta playlist es increíble. ¡Tienes muy buen gusto musical! Cada canción es una joya.')
        var color = "#00FF00";
      } else if (average_popularity > 55){
        var Comentario = document.createTextNode('Esta playlist es muy buena. Tiene una variedad de estilos y ritmos que te hacen disfrutar de la música.')
        var color = "#C9FF00"
      } else if (average_popularity > 45){
        var Comentario = document.createTextNode('Esta playlist es decente. Tiene un equilibrio entre canciones populares y otras más desconocidas.')
        var color = "#FFD700"
      } else if (average_popularity > 20){
        var Comentario = document.createTextNode('Esta playlist no es muy atractiva. Tiene algunas canciones buenas, pero otras que no pegan nada.')
        var color = "#FF8C00"
      } else {
        var Comentario = document.createTextNode('Esta playlist necesita una renovación urgente. Tal vez deberías explorar otros géneros musicales.')
        var color = "#FF0000"
      }

      var pTextNode = document.createElement("p");
      var textNode = document.createTextNode("El puntaje de tu playlist '" + playlist_name + "' es de: " + average_popularity);
      var listItem = document.createElement("li");
      var divProgressBar = document.createElement("div");
      var spotifyLogo = document.createElement("img");
      spotifyLogo.setAttribute("src", "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg");
      spotifyLogo.setAttribute("width", "30");
      spotifyLogo.setAttribute("height", "30");
      spotifyLogo.style.marginRight = "1rem";
      spotifyLogo.style.top = "7px";
      spotifyLogo.style.position = "relative";

      divProgressBar.setAttribute("class", "progress-bar");
      divProgressBar.setAttribute("data-progress", "100%");
      var pProgressBar = document.createElement("p");
      var divComentario = document.createElement("div");
      var pComentario = document.createElement("a");
      divComentario.setAttribute("class", "div-comentario");
      divComentario.appendChild(spotifyLogo);
      divComentario.appendChild(pComentario);
      pComentario.appendChild(Comentario);
      pComentario.setAttribute("class", "comentario");
      pComentario.setAttribute("href", playlist_url);
      pComentario.style.color = color;
      pComentario.style.fontSize = "18px";
      pTextNode.style.fontSize = "26px";
      pProgressBar.setAttribute("class", "progress");
      pProgressBar.setAttribute("data-progress", average_popularity);
      pProgressBar.innerHTML = "|";

      pTextNode.appendChild(textNode);
      listItem.appendChild(pTextNode);
      listItem.appendChild(divProgressBar); 
      listItem.appendChild(divComentario);
      list.appendChild(listItem);
      divProgressBar.appendChild(pProgressBar);
    }

    recetlyPllayed.appendChild(list);
    const progressNumber = document.querySelectorAll('.progress');

    for (var i = 0; i < progressNumber.length; i++) {
      var progressNum = progressNumber[i].getAttribute('data-progress');
      progressNum = parseFloat(progressNum);
      progressNumber[i].style.left = progressNum + "%";
      var progressWidth = (100 - progressNum) + "%";
      console.log(progressWidth)
      progressNumber[i].style.width = progressWidth;
    }
    
  </script>
  <p style="color: #5E6366;">* Los puntajes se calculan con base al puntaje que Spotify le asigna a cada una de las canciones teniendo en cuenta la cantidad de oyentes que estas tienen</p>
</div>
</body> 
</html>